from pathlib import Path
import configparser
import os
import re

print("[ Hackisskey Secrets Applyer ]")

if not os.path.isfile("./secrets.ini"):
  print("\n[ERROR] secrets.ini doesn't exist")
  exit(1)

config = configparser.ConfigParser()
config.read('./secrets.ini')
secrets = config["SECRETS"]
print("- secrets.ini loaded")

replace_target_list: list[str] = []

error = False

for path in Path(".").rglob("*"):
  name = path.name
  if name.endswith(".withsecrets") or ".withsecrets." in name:
    with open(path.as_posix(), "r", encoding="utf-8") as f:
      data = f.read()
      has_var = bool(re.search(r"\{\{\s*[\w]+\s*\}\}", data))
      if has_var:
        vars_found = re.findall(r"\{\{\s*([\w]+)\s*\}\}", data)
        for i in vars_found:
          if not i in secrets.keys():
            if not error:
              error = True
              print("\n")
            print(f"* \"{i}\" is not set in secrets.ini, but it exists on {path.as_posix()}")
        replace_target_list.append(path.as_posix())
      else:
        None

if error:
  exit(1)

def replace_var(match):
  key = match.group(1)
  return secrets.get(key, f"{{{{{key}}}}}")

for path in replace_target_list:
  with open(path, "r", encoding="utf-8") as f:
    data = f.read()

  extractedPath = path.replace(".withsecrets", "")
  with open(extractedPath, "w", encoding="utf-8") as f:
    result = re.sub(r"\{\{\s*([\w]+)\s*\}\}", replace_var, data)
    if extractedPath.lower().endswith(".yml") or extractedPath.lower().endswith(".yaml") or extractedPath.lower().endswith(".env"):
      result = (fr"""
#===============================================#
# __        __               _             _    #
# \ \      / /_ _ _ __ _ __ (_)_ __   __ _| |   #
#  \ \ /\ / / _` | '__| '_ \| | '_ \ / _` | |   #
#   \ V  V / (_| | |  | | | | | | | | (_| |_|   #
#    \_/\_/ \__,_|_|  |_| |_|_|_| |_|\__, (_)   #
#                                    |___/      #
# This file is generated with secrets-manager   #
# from {path}.{" "*(40-len(path))+"#" if len(path) < 40 else " #"}
#                                               #
# DO NOT EDIT THIS FILE DIRECTLY!               #
#===============================================#
""").strip()+"\n\n" + result
      
    if extractedPath.lower().endswith(".sql"):
      result = (fr"""
---------------------------------------------------
-- __        __               _             _    --
-- \ \      / /_ _ _ __ _ __ (_)_ __   __ _| |   --
--  \ \ /\ / / _` | '__| '_ \| | '_ \ / _` | |   --
--   \ V  V / (_| | |  | | | | | | | | (_| |_|   --
--    \_/\_/ \__,_|_|  |_| |_|_|_| |_|\__, (_)   --
--                                    |___/      --
-- This file is generated with secrets-manager   --
-- from {path}.{" "*(40-len(path))+"--" if len(path) < 40 else " --"}
--                                               --
-- DO NOT EDIT THIS FILE DIRECTLY!               --
---------------------------------------------------
""").strip()+"\n\n" + result
    
    f.write(result)

print("\n✅️ Successfully extracted files with secrets")
